resolver: lts-12.9

packages:
- .
- location:
    git: https://github.com/madgen/exalog.git
    commit: 586d05ce00cd47a1e9fdaac29c40002f70f1056c
  extra-dep: true
- location:
    git: git@github.com:clash-lang/ghc-typelits-natnormalise
    commit: 45080a9f50b040178e145c0e9b489c26c17a6d52
  extra-dep: true
