resolver: lts-13.18

packages:
- .
- location:
    git: https://github.com/madgen/exalog.git
    commit: d7bb1f70cdfe55c777885a29f7d89e2f68b5e1f9
  extra-dep: true
- location:
    git: git@github.com:clash-lang/ghc-typelits-natnormalise
    commit: 45080a9f50b040178e145c0e9b489c26c17a6d52
  extra-dep: true
