resolver: lts-13.18

packages:
- .
- location:
    git: https://github.com/madgen/exalog.git
    commit: 68dd035ecb8edc4cb629ff1721fd46a47ad8b4f4
  extra-dep: true
- location:
    git: git@github.com:clash-lang/ghc-typelits-natnormalise
    commit: 45080a9f50b040178e145c0e9b489c26c17a6d52
  extra-dep: true
