resolver: lts-12.9

packages:
- .
- location:
    git: https://github.com/madgen/exalog.git
    commit: b9b22d533da984c2e5c66cab38f7a66f81eee0ef
  extra-dep: true
- location:
    git: git@github.com:clash-lang/ghc-typelits-natnormalise
    commit: 45080a9f50b040178e145c0e9b489c26c17a6d52
  extra-dep: true
