resolver: lts-12.9

packages:
- .
- location:
    git: https://github.com/madgen/exalog.git
    commit: c608f5d12f79a72b278798c10e1b1f6661946d99
  extra-dep: true
- location:
    git: git@github.com:clash-lang/ghc-typelits-natnormalise
    commit: 45080a9f50b040178e145c0e9b489c26c17a6d52
  extra-dep: true
