resolver: lts-13.18

packages:
- .
- location:
    git: https://github.com/madgen/exalog.git
    commit: 4e33f607f8c621c05199ba50fdc724742ec36aa6
  extra-dep: true
- location:
    git: git@github.com:clash-lang/ghc-typelits-natnormalise
    commit: 45080a9f50b040178e145c0e9b489c26c17a6d52
  extra-dep: true
