resolver: lts-13.18

extra-deps:
- git: https://github.com/madgen/exalog.git
  commit: 7c1a3dff4a3fe616c2e02b2e029187d0c46014db
- git: git@github.com:clash-lang/ghc-typelits-natnormalise
  commit: 45080a9f50b040178e145c0e9b489c26c17a6d52
