resolver: lts-13.18

packages:
- .
- location:
    git: https://github.com/madgen/exalog.git
    commit: 87848150f1a427c5f37bf7f04997e8cc7ccb3fd5
  extra-dep: true
- location:
    git: git@github.com:clash-lang/ghc-typelits-natnormalise
    commit: 45080a9f50b040178e145c0e9b489c26c17a6d52
  extra-dep: true
